### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by xianglli** [lij55/gphost#1]
installing : greenplum-db-6.4.0-1.el7.x86_64                            50/55 
error: unpacking of archive failed on file /usr/local/greenplum-db-6.4.0/bin/postgres;5e61bb0f: cpio: read
Error unpacking rpm package greenplum-db-6.4.0-1.el7.x86_64
  Cleanup    : 1:openssl-libs-1.0.2k-12.el7.x86_64                        51/55 
error: greenplum-db-6.4.0-1.el7.x86_64: install failed

**Comment by lij55** [comment]
Could you please paste the full log of `docker build`. looks like network issue.

**Comment by lij55** [comment]
couldn't reproduce it so close it.
