### ISSUE TITLE
-bash: gpinitsystem: command not found

### ISSUE THREAD

**Issue by dsfd3f** [lij55/gphost#8]
你好，artifact/prepare.sh -s 2 -n 2 完成之后显示找不到gpinitsystem命令，请问怎么解决
[gpadmin@mdw ~]$ ls
artifact  data  env.sh  gpinitsystem_config  hostfile  master  mirror

**Comment by dxtrzhang** [comment]
try `export PATH=/usr/local/greenplum-db-xxx/bin:$PATH`

**Comment by lij55** [comment]
`source env.sh`
